config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources :fluids
  resources :nurse_notes
  resources :treatment_sheets
  resources :nurse_procedures
  resources :incident_reports
  resources :radio_test_results
  resources :lab_order_lists
  resources :medication_temps
  resources :appointments
  resources :order_requests
  resources :order_masters
  resources :bill_temps do
    resource :download, only: [:show]
    resource :download2, only: [:show]
  end
  resources :admissions
  resources :service_inventory_histories
  resources :bill_histories
  resources :categories
  resources :services_inventories
  resources :test_results
  resources :radiology_requests
  resources :medication_requests
  resources :lab_requests
  resources :clinic_documents
  resources :basic_med_records
  resources :assign_patients
  resources :patients
  resources :roles
  devise_for :users
    resources :store_requests
    resources :dispensaries
  resources :store_inventory_masters
  resources :purchase_receipts
  resources :admission_review_notes
    resources :assigned_requests
    resources :store_inventory_categories
    resources :store_purchases
    resources :dispensaries
    resources :store_purchases do
      post :append, on: :collection
    end
  get 'home/index'

   devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  get 'requests' => 'home#requests'

  post 'update_temp' => 'store_requests#update_temp'

  post 'update_qtytemp' => 'assign_patients#update_qtytemp'

  get 'assigned_request_page' => 'home#assigned_requests'

  get 'receipts' => 'home#receipts'

  get 'import_csv' => 'store_inventory_masters#import_csv' 

  post 'import_file', to: 'store_inventory_masters#import_file', as: 'import_file'

  get 'item_purchase' => 'home#item_purchase'

  get 'categories' => 'home#categories'

  get 'dispensing' => 'home#dispensing'

  get 'confirm_dispense' => 'assigned_requests#confirm_dispense'

  post 'custom_dispense' => 'dispensaries#custom_dispense'
  get 'checkout' => 'store_requests#checkout'
  post 'retrive' => 'assigned_requests#retrive'
  get 'search' => 'store_inventory_masters#search'
  post 'back_to_form' => 'store_requests#back_to_form'
  post 'submit_to_dispense' => 'assigned_requests#submit_to_dispense'

  post 'modal_form' => 'store_requests#modal_form'

  get 'items_by_category/:store_inventory_category_id', to: 'store_requests#items_by_category'
  get '/store_requests_search' => 'store_requests#store_requests_search'

  get 'store_requests/update_items', as: 'update_items'

  root 'home#index'

  get '/users' => 'users#index'

  get '/users/new' => 'users#new', :as => 'new_user'
  get '/users/:id/edit' => 'users#edit', :as => 'edit_user'
  get '/users/:id' => 'users#show', :as => 'user'
  patch '/users/:id' => 'users#update', :as => 'update_user'
  patch '/patients/:id' => 'patients#update', :as => 'update_patient'
  post 'create_user' => 'users#create', as: :create_user

  post      'update_clinic_documents'                          =>     'clinic_documents#update_clinic_documents'

  get       'remove_contact'                          =>     'users#remove_contact'

  get       'patients_form'                          =>     'patients#patients_form'
  get  'show_patients'          =>     'patients#show_patients'
  get  'edit_patients'          =>     'patients#edit_patients'
  get  'edit_docs'          =>     'assign_patients#edit_docs'
  get  'assign_a_patient'          =>     'patients#assign_a_patient'
  get  'basic_medical'          =>     'assign_patients#basic_medical'
  get  'assign_a_patient2'          =>     'basic_med_records#assign_a_patient2'

  get  'procedure_list'          =>     'assign_patients#procedure_list'

  get 'view_procedure_record' =>     'nurse_procedures#view_procedure_record'

  get 'incident_form'  =>  'incident_reports#incident_form'
  get 'view_report'  =>  'incident_reports#view_report'

  get  'clinic_documentation'          =>     'assign_patients#clinic_documentation'
    get  'appt_documentation'          =>     'appointments#appt_documentation'
  get  'view_documentation'          =>     'assign_patients#view_documentation'
  get  'assign_lab'          =>     'assign_patients#assign_lab'
  get  'assign_med'          =>     'assign_patients#assign_med'
  get  'show_details'          =>     'assign_patients#show_details'
  get  'docs'          =>     'assign_patients#docs'
  get  'lab_docs'          =>     'lab_requests#lab_docs'
  get  'lab_form'          =>     'lab_requests#lab_form'
  get  'view_lab'          =>     'lab_requests#view_lab'
  get  'delete_lab_record'          =>     'lab_requests#delete_lab_record'
  get  'med_docs'          =>     'medication_requests#med_docs'
  get  'med_form'          =>     'medication_requests#med_form'
  get  'view_med'          =>     'medication_requests#view_med'
  get  'other_med'          =>     'medication_requests#other_med'
  get  'other_radio'          =>     'radiology_requests#other_radio'

  get  'radio_docs'          =>     'radiology_requests#radio_docs'
  get  'radio_form'          =>     'radiology_requests#radio_form'
  get  'view_radio'          =>     'radiology_requests#view_radio'
  get 'delete_radio_record'  =>     'radiology_requests#delete_radio_record'

  get 'medical_records'  =>     'radiology_requests#medical_records'

  get  'other_lab'          =>     'lab_requests#other_lab'
  get  'lab_history'          =>     'lab_requests#lab_history'
  get  'enter_results'          =>     'lab_requests#enter_results'
  get  'lab_medical_records'          =>     'lab_requests#lab_medical_records'
  get  'enter_radio_results'   =>     'radiology_requests#enter_radio_results'
  get  'results'          =>     'test_results#results'
  get  'patient_admission'          =>     'admissions#patient_admission'
  get  'admission_doc'          =>     'admissions#admission_doc'
  get 'patient_bill'    => 'bill_histories#patient_bill'
  get 'bill_open'    => 'bill_temps#bill_open'
  get 'previous_bills'    => 'bill_temps#previous_bills'
  get 'outstanding'   => 'bill_temps#outstanding'
  get 'paid'    => 'bill_temps#paid'
  get 'delete_bill_record'    => 'bill_temps#delete_bill_record'

  get 'previous_medication'  => 'medication_temps#previous_medication'

  get 'view_note'  => 'admissions#view_note'
  get 'view_discharge_note' => 'admissions#view_discharge_note'
  get  'view_nurse_record'          =>     'basic_med_records#view_nurse_record'
  post 'assign_to_a_doctor '  =>  'assign_patients#assign_to_a_doctor'
  get  'main_test'          =>     'test_results#main_test'
  get  'indi_radio_result'          =>     'radio_test_results#indi_radio_result'

  get 'close_request' =>  'medication_requests#close_request'
  get 'open_request'  =>   'medication_requests#open_request'

  get 'close_request_rad' =>  'radiology_requests#close_request_rad'
  get 'open_request_rad'  =>   'radiology_requests#open_request_rad'

  get  'order_records'          =>     'order_requests#order_records'
  get  'make_order'          =>     'order_requests#make_order'
  get  'view_order'          =>     'order_requests#view_order'

  get 'delete_order_record' =>     'order_requests#delete_order_record'

  get 'add_room'    =>      'admissions#add_room'
  get 'edit_room'    =>      'admissions#edit_room'
  post 'add_a_room'    =>      'admissions#add_a_room'

  get 'discharge_patient'    =>      'admissions#discharge_patient'
  get 'discharged_list'    =>      'admissions#discharged_list'
  get 'discharged_list_nurses'    =>      'admissions#discharged_list_nurses'
  get 'nurse_admission_list' => 'admissions#nurse_admission_list'

  get 'admission_vitals' => 'admissions#admission_vitals'
  get 'discharge_note' => 'admissions#discharge_note'
  post 'a_discharge_note' => 'admissions#a_discharge_note'

  get 'nurse_admission_vitals_history' =>  'basic_med_records#nurse_admission_vitals_history'
  get 'admission_vital_graph' =>  'basic_med_records#admission_vital_graph'
  get  'admission_basic_medical'          =>     'basic_med_records#admission_basic_medical'

  get  'doctor_admission_vitals_doc'          =>     'admissions#doctor_admission_vitals_doc'
  get  'view_doctor_admission_doc'          =>     'admissions#view_doctor_admission_doc'

     get  'write_admission_review'          =>     'admissions#write_admission_review'
get  'display_admission_review'          =>     'admissions#display_admission_review'

  get 'close_order'  =>   'order_requests#close_order'

  get 'patient_appointment' => 'appointments#patient_appointment'

  get 'reception_patient' => 'patients#reception_patient'
  post 'reception_appointment' => 'appointments#reception_appointment'
  get 'doctor_appointment' => 'appointments#doctor_appointment'

  get 'open_med_temp'  => 'medication_temps#open_med_temp'
  get 'close_med_request'   => 'medication_temps#close_med_request'
  get 'delete_med_record'   => 'medication_temps#delete_med_record'

  get 'print_bill'   => 'bill_temps#print_bill'
  get 'print_all_bill'   => 'bill_temps#print_all_bill'

  post 'basic_vitals' => 'assign_patients#basic_vitals'

  get 'import_csv_file' => 'services_inventories#import_csv_file', as: :import_csv_file
  post 'import' => 'services_inventories#import', as: :import

   get  'view_vitals'          =>     'assign_patients#view_vitals'

   get 'print_labresults'   => 'lab_requests#print_labresults'
   get 'print_pharmacy'   => 'bill_temps#print_labresults'
   get 'print_xray'   => 'bill_temps#print_labresults'
   get 'print_ultrasound'   => 'bill_temps#print_labresults'

   get 'view_reciept'   => 'bill_temps#view_reciept'

   get 'set_orders'   => 'home#set_orders'

   get 'patient_profile'   => 'patients#patient_profile'

    get 'patient_treatment' => 'treatment_sheets#patient_treatment'
   get 'new_treatment' => 'treatment_sheets#new_treatment'

   get 'nurses_note' => 'basic_med_records#nurses_note'

app/models/home.rb
class Home < ApplicationRecord

    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_confirm_dispense.html.erb
<%= simple_form_for(@dispensary, url: confirm_dispense_path) do |f| %>
  <div id="pager">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title"> select all items</h4>
          <button type="button" class="close" data-dismiss="modal">
            &times;
          </button>
        </div>
        <div class="modal-body" id = 'check_form'>
          <div class="table-responsive">
            <table class="table table-hover mb-0">
              <thead>
                <tr>
                  <th class="pt-0"> check box </th>
                  <th class="pt-0"> Item Name </th>
                  <th class="pt-0"> Quantity </th>
                  <th class="pt-0"> Manufacturer </th>
                  <th class="pt-0"> Selling Price </th>
                </tr>
              </thead>
              <tbody>
                <% if @store_items_save.nil? %>
                  <% " Empty Store" %>
                <% else %>
                  <tr>
                    <%= @store_items_save.each do |vals| %>
                      <td><%= check_box_tag ("check_box[id][]") %> </td>
                      <td id="name_of_items"><%= vals.assigned_item_name  %></td>
                      <td id="quantity_use"><%= f.input :quantity, input_html: { multiple:true } ,label:false   %></td>
                      <td id="name_of_items"><%= vals.assigned_item_manufacturer  %></td>
                      <td id="name_of_items"><%= vals.assigned_item_selling_price  %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
              <div class="form-actions">
                <%= f.button :submit, "Submit",class: 'btn btn-primary btn-lg', data: {"disable-with": "submit......"} %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/home/assigned_requests.html.erb
<style>
  .blocktext {
      margin-left: auto;
      margin-right: auto;
  
      margin: 0;
    position: relative;
    left: 50%;
    margin-right: -50%;
  }
</style>
<main>
  <body class="sidebar-dark">
    <div class="main-wrapper">
      <div class="row">
        <div class="col-12">
          <h1 class="blocktext">List of Assigned Items</h1>
          <div class="separator mb-5"></div>
        </div>
      </div>
      <p>
        <%=form_tag assigned_requests_path, method: :get,class:"lus" do %>
          <%= select_tag "category", options_from_collection_for_select(@show_categories, "id", "name")%>
          <%= submit_tag "Search" %>
        <% end %>
      </p>
      <%= simple_form_for(@dispensary, url: confirm_dispense_path, :method => :get, :remote => true) do |f| %>
        <div class="row mb-12">
          <div class="col-12 mb-12">
            <div class="card">
              <div class="card-body">
                <div class="table-responsive bs-example widget-shadow">
                  <table class="table table-bordered">
                    
                    <!-- User ID 5: Pharmacist // User ID 10 : Dispensary technologist -->
                    <% if current_user.role_id == 5 || current_user.role_id == 10 %>
                      <thead>
                        <tr>
                         
                          <th>Item Name</th>
                          <th>Item Category</th>
                          <th>Quantity </th>
                          <th>Selling Price </th>
                          <th>Role</th>
                          <th>Manufacturer </th>
                          <th>Received By </th>
                          <th>Date assigned</th>
                          <th>Comments</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                          <% @assigned_requests.each do |assigned_request| %>
                            <tr>
                              
                              <td><%= assigned_request.item_name %></td>
                              <td><%= assigned_request.category_name %></td>
                              <td><%= assigned_request.assigned_quantity %></td>
                              <td><%= assigned_request.selling_price %></td>
                              <td><%= assigned_request.cost_price %></td>
                              <td><%= assigned_request.manufaturer_name %></td>
                              <td><%= assigned_request.users_username %></td>
                              <td><%= assigned_request.assigned_date %></td>
                              <td><%= assigned_request.comments %></td>
                            </tr>
                          <% end %>
                      </tbody>
                    <% else %>
                      <thead>
                        <tr>
                          
                          <th>Item Name</th>
                          <th>Item Category</th>
                          <th>Quantity </th>
                          <th>Received By </th>
                          <th>Date assigned</th>
                          <th>Comments</th>
                          <th colspan="3"></th>
                        </tr>
                      </thead>
                      <tbody>
                          <% @assigned_requests.each do |assigned_request| %>
                            <tr>
                             
                              <td><%= assigned_request.item_name %></td>
                              <td><%= assigned_request.category_name %></td>
                              <td><%= assigned_request.assigned_quantity %></td>
                              <td><%= assigned_request.users_username %></td>
                              <td><%= assigned_request.assigned_date %></td>
                              <td><%= assigned_request.comments %></td>
                            </tr>
                          <% end %>
                      </tbody>
                    <% end %>
                  </table>
                </div>
              </div>
            </div>
          </div>
          <div style="margin-top: 80px;">
            <%= will_paginate @assigned_requests %>
          </div>
         
      
        </div>
      <% end %>
    
    </div>
  </body>
</main>
<script>
  $('#caty-button').on("click", function(){
    var cbxs = $('input[type="checkbox"]');
    cbxs.prop("checked", !cbxs.prop("checked"));
  });
</script>
<!-- Modal Call  -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/home/categories.html.erb
  <style>
  .blocktext {
      margin-left: auto;
      margin-right: auto;
  
      margin: 0;
    position: relative;
    left: 50%;
    margin-right: -50%;
  }
</style>
<main>
  <body class="sidebar-dark">
    <div class="main-wrapper">
      <div class="row">
        <div class="col-12">
          <h1 class="blocktext">Inventory Categories</h1>
          <div class="separator mb-5"></div>
        </div>
      </div>
      <div class="row mb-12">
        <div class="col-12 mb-12">
          <div class="card">
            <div class="caty-caty">
              <button type="button" id="caty-button" class="btn btn-success" style="width:max-content;">
                <%=link_to "Create New Category", new_store_inventory_category_path %>
              </button>
            </div>
            <div class="card-body">
              <div class="table-responsive bs-example widget-shadow">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th class="pt-0">ID</th>
                      <th class="pt-0">Category </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @store_inventory_categories.each do |inventory_cat| %>
                      <tr class="tdd">
                        <td><%=inventory_cat.id%></td>
                        <td><%=inventory_cat.name%></td>
                        <td><span class="badge badge-warning"><%= link_to 'Edit', edit_store_inventory_category_path(inventory_cat) %></span></td>
                        <td><span class="badge badge-danger"><%= link_to 'Delete', inventory_cat, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
                      </tr>
                    </tbody>
                  <% end %>
                </table>
                <div style="margin-top:-25px;">
                  <%= will_paginate @store_inventory_categories %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</main>

app/views/home/confirm_dispense.js.erb
$("#myModal").find(".modal-content").html("<%= escape_javascript (render partial: 'assigned_requests/confirm_dispense') %>");
$("#myModal").modal();

app/views/home/item_purchase.html.erb
<style>
  .blocktext {
      margin-left: auto;
      margin-right: auto;
  
      margin: 0;
    position: relative;
    left: 50%;
    margin-right: -50%;
  }
</style>
<main>
  <body class="sidebar-dark">
    <div class="main-wrapper">
      <div class="row">
        <div class="col-12">
          <h1 class="blocktext">Item Purchased</h1>
          <div class="separator mb-5"></div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col-12 mb-4">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive bs-example widget-shadow">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th class="pt-0">Category Name</th>
                      <th class="pt-0">Item Name</th>
                      <th class="pt-0">Quantity</th>
                      <th class="pt-0">Cost Price</th>
                      <th class="pt-0">Date of Purchase </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @store_purchases.each do |items_puchase| %>
                      <tr>
                        <%# <!-- <td><%= check_box_tag "assigned_requests_id",new_assigned_request_path(:id =>items_puchase.id) %> </td>
                      <td><%= items_puchase.name %></td>
                      <td><%= items_puchase.item_name %></td>
                      <td><%= items_puchase.quantity %></td>
                      <td><%= items_puchase.cost_price %></td>
                      <td><%= items_puchase.date_of_purchase %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <div class="blocktext">
              <button type="button" id="caty-button" class="btn btn-success" style="width:max-content;">
                <%= link_to 'Create New Store Purchase',new_store_purchase_path  %>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>
</main>

app/views/home/receipts.html.erb
 <style>
  .blocktext {
      margin-left: auto;
      margin-right: auto;
  
      margin: 0;
    position: relative;
    left: 50%;
    margin-right: -50%;
  }
</style>
<main>
  <body class="sidebar-dark">
    <div class="main-wrapper">
      <div class="row">
        <div class="col-12">
          <h1 class="blocktext">Store Receipts</h1>
          <div class="separator mb-5"></div>
        </div>
      </div>
      <div class="row mb-4">
        <div class="col-12 mb-4">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive bs-example widget-shadow">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <%# <th class="pt-0">#</th> %>
                      <th class="pt-0">Purchase_Item</th>
                      <th class="pt-0">Receipt_Image</th>
                      <th class="pt-0">User</th>
                      <th class="pt-0">Comments</th>
                      <th class="pt-0">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%  @purchase_receipts.each do |purchase_list| %>
                      <tr class="tdd">
                        <td><%=purchase_list.item_name%></td>
                        <td><%=purchase_list.image%></td>
                        <td><%=purchase_list.user_id%></td>
                        <td><%=purchase_list.comments%></td>
                        <td><%=purchase_list.status%></td>
                      </tr>
                    </tbody>
                  <% end %>
                </table>
              </div>
            </div>
            <div class="caty-caty" style="margin-top: -120px; margin-bottom: 150px;">
              <button type="button" id="caty-button" class="btn btn-success" style="width:max-content;">
                <%=link_to "Upload Receipt", new_purchase_receipt_path %>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</main>

app/views/home/requests.html.erb
<style>
  .blocktext {
      margin-left: auto;
      margin-right: auto;
  
      margin: 0;
    position: relative;
    left: 50%;
    margin-right: -50%;
  }
</style>
<main>
  <body class="sidebar-dark">
    <div class="main-wrapper">
      <div class="row">
        <div class="col-12">
          <h1 class="blocktext">  Requested Items</h1>
          <div class="separator mb-5"></div>
        </div>
      </div>
      <p>
        <%=form_tag requests_path, method: :get,class:"lus" do %>
          <%= select_tag "category", options_from_collection_for_select(@show_categories, "id", "name")%>
          <%= submit_tag "Search" %>
        <% end %>
      </p>
      <%= simple_form_for(@store_request, url: retrive_path) do |f| %>
        <div class="d-flex justify-content-between align-items-baseline mb-2">
          <div class="caty-caty" style="float: right; margin-right: -500px;">
            <button type="button" id="catty-button" class="btn btn-success" style="width:max-content;">
              <%=link_to "Make A Request", new_store_request_path %>
            </button>
          </div>
        </div>
        <div class="row mb-12">
          <div class="col-12 mb-12">
            <div class="card">
              <div class="card-body">
                <div class="table-responsive bs-example widget-shadow">
                  <table class="table table-bordered">
                      <button type="button" id="cato-button1" class="btn btn-success" style="float: left; color:white;">Check All</button>
                        <% if current_user.role_id == 9 %>
                    <thead>
                      <tr>
                        <th> </th>
                        <th class="pt-0">Category Name</th>
                        <th class="pt-0">Item Name </th>
                        <th class="pt-0">Quantity Requested</th>
                        <th class="pt-0">Date Requested</th>
                        <th class="pt-0">Request User</th>
                        <th class="pt-0">Request User Role</th>
                        <th class="pt-0">Comments</th>
                        <th class="pt-0">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @store_requests.each do |request_list| %>
                        <tr class="tdd">
                          <div class="items_row">
                            <td><%= check_box_tag ("store_request[id][]"),checked_value = request_list.id %> </td>
                            <td><%=request_list.category_name%></td>
                            <td><%=request_list.item_name%></td>
                            <td><%=request_list.requested_quantity%></td>
                            <td><%=request_list.date_requested%></td>
                            <td><%=request_list.user_fullname%></td>
                            <td><%=request_list.role_name%></td>
                            <td><%=request_list.comments%></td>

                            <td class="requests-<%= request_list.id %>">
                              <%= link_to "#{ request_list.status ? 'Open Request' : 'Closed Request' }",
                              {remote: :true, class: "badge badge-#{ request_list.status  ? 'success' : 'warning' }"} %>
                            </td>	
                          </div>
                        </tr>
                      </tbody>
                     

                    <% end %>
                  </table>
                  <div class="load-more-container">
                    <%= link_to "Load More", requests_path, class: "load-more" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="caty-catz" style="margin-left: 435px;">
          <button type="button" id="caty-button" class="btn btn-success" style="width:max-content; color:white;float: left;">
            <%= f.button :submit, 'Assigned Checked Items', disabled:true,   :id => 'requestSubmitbtn', :style =>"color:white;" %>
          </button>
        </div>
         <% else%>
                      <thead>
                      <tr>
                        
                        <th class="pt-0">Category Name</th>
                        <th class="pt-0">Item Name </th>
                        <th class="pt-0">Quantity Requested</th>
                        <th class="pt-0">Date Requested</th>
                        <th class="pt-0">Request User</th>
                        <th class="pt-0">Request User Role</th>
                        <th class="pt-0">Comments</th>
                        <th class="pt-0">Status</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @store_requests.each do |request_list| %>
                        <tr class="tdd">
                          <div class="items_row">
                            
                            <td><%=request_list.category_name%></td>
                            <td><%=request_list.item_name%></td>
                            <td><%=request_list.requested_quantity%></td>
                            <td><%=request_list.date_requested%></td>
                            <td><%=request_list.user_fullname%></td>
                            <td><%=request_list.role_name%></td>
                            <td><%=request_list.comments%></td>

                            <td class="requests-<%= request_list.id %>">
                              <%= link_to "#{ request_list.status ? 'Open Request' : 'Closed Request' }",
                              {remote: :true, class: "badge badge-#{ request_list.status  ? 'success' : 'warning' }"} %>
                            </td>	
                          </div>
                        </tr>
                      </tbody>
                       <% end %>
                  </table>
                  <div class="load-more-container">
                    <%= link_to "Load More", requests_path, class: "load-more" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
      <% end %>
      <%end%>
    </body>
  </main>
 
<script>

  var sendbtn = document.getElementById('requestSubmitbtn');

  $('#cato-button1').on("click", function(){
    var cbxs = $('input[type="checkbox"]');

    var a =  cbxs.prop("checked", !cbxs.prop("checked"));
  
    //checking if cbx is checked
    if ((cbxs).is(":checked") ){
      console.log('a passed')
      sendbtn.disabled = false;
    }

    else{
      console.log('a didnt pass')
      sendbtn.disabled = true;
    }
      
  });
  

  $('input:checkbox').change(function(){

    var len= document.querySelectorAll('input[type=checkbox]:checked').length
    console.log(len + " lebgthhhhhh")
     
    if(len > 0) {

      console.log('working oayyy')
      sendbtn.disabled = false;
        
    } 
    else {
      console.log('working 2cc')
      sendbtn.disabled = true;
        
    }
  });

</script>

 
 
<!-- 
  <script>

    $(document).ready(function() {

    var cbxs = $('input[type="checkbox"]');

  
  
    // $('#requestSubmitbtn').prop("disabled", true);

    $('#cato-button1').on("click", function(){
         console.log("default check is " + cbxs.checked)

    
     
        cbxs.prop("checked", !cbxs.prop("checked"));
        

            //     $('input[type="checkbox"]').each(function() {
    //       if ($(this.checked))
    //       {
    //           empty = false;
    //           console.log(empty + ' when box is checeked')

    //       } else {
    //         empty = true; 
    //           console.log(empty + ' when box is not checeked')
    //       }
    //     });

     
      

      // $('#requestSubmitbtn').prop("disabled", false);

    });
    });

  </script> 

-->

app/views/home/retrive.js.erb
$("#myModal").find(".modal-content").html("<%= escape_javascript (render 'home/retrive') %>");
$("#myModal").modal();